In [5]:
import os
import cv2
from tqdm import tqdm
import numpy as np
import math
import json
import open3d as o3d
import copy
import csv
import matplotlib.pyplot as plt

import read_raw_file as RRF
import preprocess as PRE
import marker_detection


In [2]:
path = r'D:\StageE23\Data\Ete_2022\Participant02\BD\Libre\Prise01'
save_path1 = path + '/intensity_removed_bg/'
save_path2 = path + '/xyz_removed_bg/'
intensity_path = path + '/intensity/'
xyz_path = path + '/xyz/'

os.makedirs(save_path1, exist_ok=True)
os.makedirs(save_path2, exist_ok=True)

for filename in tqdm(os.listdir(intensity_path)):
        index_I = filename.find('_I') + 1
        xyz_file = filename[:index_I] + 'XYZ_' + filename[index_I+2:-4] + '.raw'
        image_path = os.path.join(intensity_path, filename)
        pc_path = os.path.join(xyz_path, xyz_file)
        xyz = PRE.read_single_xyz_raw_file(pc_path)
        image = cv2.imread(image_path, cv2.IMREAD_GRAYSCALE)
        
        removed_bg_points, image_no_bg = PRE.remove_bg(xyz, image)
        
        save_image_path = os.path.join(save_path1, filename)
        cv2.imwrite(save_image_path, image_no_bg)

        pc_removed_bg = o3d.geometry.PointCloud()
        pc_removed_bg.points = o3d.utility.Vector3dVector(removed_bg_points)
        cl, ind = pc_removed_bg.remove_statistical_outlier(nb_neighbors=40,
                                                std_ratio=1.6)
        inlier_removed_bg = pc_removed_bg.select_by_index(ind)

        save_xyz_path = os.path.join(save_path2, xyz_file[:-4] + '.ply')
        o3d.io.write_point_cloud(save_xyz_path, inlier_removed_bg)

100%|██████████| 92/92 [02:01<00:00,  1.32s/it]


In [89]:
pc0 = o3d.io.read_point_cloud(r'D:\StageE23\Data\Ete_2022\Participant02\BD\Libre\Prise01\xyz_removed_bg\BD_libr_01_001034_XYZ_0.ply')
pc1 = o3d.io.read_point_cloud(r'D:\StageE23\Data\Ete_2022\Participant02\BD\Libre\Prise01\xyz_removed_bg\BD_libr_01_001035_XYZ_1.ply')
pc40 = o3d.io.read_point_cloud(r'D:\StageE23\Data\Ete_2022\Participant02\BD\Libre\Prise01\xyz_removed_bg\BD_libr_01_001082_XYZ_40.ply')
pc50 = o3d.io.read_point_cloud(r'D:\StageE23\Data\Ete_2022\Participant02\BD\Libre\Prise01\xyz_removed_bg\BD_libr_01_001094_XYZ_50.ply')
pc72 = o3d.io.read_point_cloud(r'D:\StageE23\Data\Ete_2022\Participant02\BD\Libre\Prise01\xyz_removed_bg\BD_libr_01_001120_XYZ_72.ply')

o3d.visualization.draw_geometries([pc0])

In [96]:
def crop_pc(pc):
    pc_array = np.asarray(pc.points)
    print(pc_array)
 
    legs = np.where(pc_array[:,0] < -300)
    head = np.where(pc_array[:,0] > np.max(pc_array[:,0])-300)
    armR = np.where(pc_array[:,1] > np.max(pc_array[:,1])-90)
    armL = np.where(pc_array[:,1] < np.min(pc_array[:,1])+90)

    mask = np.ones((pc_array.shape[0],3), dtype=bool)
    mask[legs] = False
    mask[head] = False
    mask[armR] = False
    mask[armL] = False
    #mask.reshape((500123, 3))

    back = np.array(pc_array[mask], dtype=np.float64)

    pc = np.array(back.reshape((back.shape[0]//3, 3)))

    pc_cropped = o3d.geometry.PointCloud()
    pc_cropped.points = o3d.utility.Vector3dVector(pc)
    
    return pc_cropped

pc_center = crop_pc(pc0)
o3d.visualization.draw_geometries([pc_center])


In [5]:
def draw_registration_result(source, target, transformation):
    source_temp = copy.deepcopy(source)
    target_temp = copy.deepcopy(target)
    source_temp.paint_uniform_color([1, 0.706, 0])
    target_temp.paint_uniform_color([0, 0.651, 0.929])
    source_temp.transform(transformation)
    o3d.visualization.draw_geometries([source_temp, target_temp])

In [115]:
body0 = crop_pc(pc0)
body1 = crop_pc(pc1)
body40 = crop_pc(pc40)
body50 = crop_pc(pc50)
body72 = crop_pc(pc72)

trans_init = np.identity(4)

icp1 = o3d.pipelines.registration.registration_icp(body0, body1, 10, trans_init, o3d.pipelines.registration.TransformationEstimationPointToPoint())
print(icp1.transformation)

icp50 = o3d.pipelines.registration.registration_icp(body40, body50, 10, trans_init, o3d.pipelines.registration.TransformationEstimationPointToPoint())
print(icp50.transformation)

draw_registration_result(body40, body50, icp50.transformation)

[[-185.04086304 -203.23529053 1796.91711426]
 [-185.97872925 -203.29910278 1797.43640137]
 [-186.9108429  -203.35600281 1797.89440918]
 ...
 [-230.64271545  203.10369873 1842.90161133]
 [-235.64268494  203.52252197 1846.41516113]
 [-236.64251709  203.60415649 1847.09814453]]
[[-186.86268616 -203.30361938 1797.43127441]
 [-187.8059082  -203.37220764 1797.99243164]
 [-188.70266724 -203.39013672 1798.10559082]
 ...
 [-236.66604614  203.62440491 1847.28186035]
 [-237.67375183  203.7121582  1848.01965332]
 [-238.79000854  203.891922   1849.59216309]]
[[ 354.95379639 -204.87136841 2043.01904297]
 [ 354.03741455 -204.92196655 2043.60705566]
 [ 352.96954346 -204.88502502 2043.32165527]
 ...
 [ 481.1847229   259.90771484 1883.74841309]
 [ 482.19720459  260.88504028 1883.8815918 ]
 [ 480.70889282  260.58505249 1881.8260498 ]]
[[-318.1159668  -206.51820374 1825.18615723]
 [-319.02301025 -206.5242157  1825.16357422]
 [-294.55819702 -205.47015381 1825.79199219]
 ...
 [ 402.31640625  386.63476562 18

In [16]:
RST = icp50.transformation
T = RST[0:3, 3]
print(T)
len_T = np.linalg.norm(T)
print(f'Distance de translation : {len_T} mm')
RS = RST[0:3, 0:3]
print(RS)
S = np.zeros((3,3))
S[0,0] = np.linalg.norm(RS[:,0])
S[1,1] = np.linalg.norm(RS[:,1])
S[2,2] = np.linalg.norm(RS[:,2])
print(S)
R = np.matmul(RS, np.linalg.inv(S)) #S est la matrice identité, donc R=RS, aucun scaling
print(R)

[ -8.38374302 125.10506713  -1.46606492]
Distance de translation : 125.39423557208771 mm
[[ 0.99497345 -0.10012251  0.00182253]
 [ 0.10003751  0.99297978 -0.06311614]
 [ 0.00450961  0.06298121  0.99800452]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[ 0.99497345 -0.10012251  0.00182253]
 [ 0.10003751  0.99297978 -0.06311614]
 [ 0.00450961  0.06298121  0.99800452]]


In [12]:
Tr = np.trace(R)
cos_rot = (Tr-1)/2
angle_rot = np.degrees(np.arccos(cos_rot))
print(angle_rot)

axis_rot = np.multiply(1/np.sqrt((3-Tr)*(1+Tr)), np.array([R[2,1]-R[1,2], R[0,2]-R[2,0], R[1,0]-R[0,1]]))
print(axis_rot)

6.793527411413739
[ 0.53299279 -0.01135781  0.84604355]


In [13]:
def IsRotationMatrix(R):
    Rt = np.transpose(R)
    shouldBeIdentity = np.dot(Rt, R)
    I = np.identity(3, dtype = R.dtype)
    n = np.linalg.norm(I - shouldBeIdentity)
    return n < 1e-6

def RotationMatrixToEulerAngles(R):
    assert(IsRotationMatrix(R))

    sy = math.sqrt(R[0,0] * R[0,0] + R[1,0] * R[1,0])

    singular = sy < 1e-6

    if not singular:
        y = math.atan2(R[2,1], R[2,2])
        x = math.atan2(-R[2,0], sy)
        z = math.atan2(R[1,0], R[0,0])
    else:
        y = math.atan2(-R[1,2], R[1,1])
        x = math.atan2(-R[2,0], R[1,1])
        z = 0

    return np.array([np.degrees(x),np.degrees(y),np.degrees(z)])

print(RotationMatrixToEulerAngles(R))

[-0.2583823   3.61098395  5.74138883]


In [49]:
def get_marker_array(path):
    marker_array = np.zeros((len(os.listdir(path+'/Preprocessed/')), 8, 3))
    
    with open(path+'/Positions/coordonnees_xyz.csv', 'r') as csvfile:
        reader = csv.reader(csvfile, delimiter=';')
        j = 0
        for row in reader: #skip headline
            if j == 0:
                entete = row[1::3]
                labels = [e[:-2] for e in entete]
                print(labels)
            elif j > 0:
                im = int(row[0])
                row = [float(i) for i in row[1:]]
                row_by_label = [[row[3*i], row[3*i+1], row[3*i+2]] for i in range(0,int(len(row)/3))]
                marker_array[im-1] = row_by_label
            j += 1
        
        return marker_array

marker_array = get_marker_array(r'D:\StageE23\Data\Ete_2022\Participant06\autocorrection\Prise02')
print(marker_array)
    

['C7', 'T1', 'L', 'IG', 'ID', 'D', 'G', 'T2']
[[[  45.05211    115.321014  1931.0319   ]
  [  56.52221      7.988124  1907.0336   ]
  [  51.24678   -149.72554   1914.9932   ]
  ...
  [ 143.6735     -39.07152   1890.8992   ]
  [  -9.318874   -42.7877    1895.0947   ]
  [  62.849358   -62.38438   1901.2242   ]]

 [[  41.29367    116.27257   1931.2318   ]
  [  54.668633     8.916767  1907.1565   ]
  [  50.31163   -148.78723   1914.9814   ]
  ...
  [ 141.85144    -38.155533  1891.2617   ]
  [ -13.936964   -41.88554   1896.0045   ]
  [  61.022797   -62.40968   1902.028    ]]

 [[  40.374317   116.33418   1932.2648   ]
  [  52.826744     8.9192505 1907.712    ]
  [  49.378696  -148.78873   1915.0133   ]
  ...
  [ 140.01562    -38.157585  1891.4359   ]
  [ -11.171951   -41.897377  1896.548    ]
  [  60.107346   -61.4945    1902.3949   ]]

 ...

 [[  50.028057   118.79053   1941.4761   ]
  [  66.17368      9.89963   1917.5833   ]
  [  56.158573  -147.56752   1923.4088   ]
  ...
  [ 153.06985  

In [52]:
target_nb = 20
distances = np.zeros((len(marker_array[:,0,0]), 8, 3))
for i in range(len(marker_array[:,0,0])):
    distances[i] = np.subtract(marker_array[i], marker_array[target_nb])

print(distances)
print(np.median(distances, 0))


[[[  9.14657    -3.681256  -14.0672   ]
  [  6.196908   -3.78307   -11.5393   ]
  [  4.437156   -3.01176    -9.6839   ]
  ...
  [  5.06591    -6.122004  -19.4029   ]
  [  0.024451   -1.737106   -4.9951   ]
  [  6.154702   -3.364364  -11.1314   ]]

 [[  5.38813    -2.7297    -13.8673   ]
  [  4.343331   -2.854427  -11.4164   ]
  [  3.502006   -2.07345    -9.6957   ]
  ...
  [  3.24385    -5.206017  -19.0404   ]
  [ -4.593639   -0.834946   -4.0853   ]
  [  4.328141   -3.389664  -10.3276   ]]

 [[  4.468777   -2.66809   -12.8343   ]
  [  2.501442   -2.8519435 -10.8609   ]
  [  2.569072   -2.07495    -9.6638   ]
  ...
  [  1.40803    -5.208069  -18.8662   ]
  [ -1.828626   -0.846783   -3.5418   ]
  [  3.41269    -2.474484   -9.9607   ]]

 ...

 [[ 14.122517   -0.21174    -3.623    ]
  [ 15.848378   -1.871564   -0.9896   ]
  [  9.348949   -0.85374    -1.2683   ]
  ...
  [ 14.46226    -1.976004    5.6793   ]
  [ 16.619215   -2.622063   -6.6269   ]
  [ 14.891518   -0.927214   -0.4014   ]]

 [